--- dllama_orig/distributed-llama/Makefile	2026-05-16 13:23:14
+++ dllama_patched/Makefile	2026-05-16 13:12:03
@@ -8,7 +8,7 @@
 ifdef DEBUG
 	CXXFLAGS += -g -fsanitize=address
 else
-	CXXFLAGS += -O3
+	CXXFLAGS += -O3 -flto -ffast-math -funroll-loops -mcpu=cortex-a76 -mtune=cortex-a76 -march=armv8.2-a+fp16+dotprod+rcpc -fipa-pta -fipa-icf -falign-functions=64 -falign-loops=64
 endif
 
 ifdef WVLA
